### ISSUE TITLE
taxa_are_rows bug in write.dataset.biom function

### ISSUE THREAD

**Issue by zhilongjia** [itsmisterbrown/marker_gene_processing_scrips#1]
the current version (`data = as.matrix(t(phyloseq::otu_table(ps)))`) can only deal with ps object whose taxa are in column.

should be:

     #generate biom file
     suppressWarnings(ps.b <- biomformat::make_biom(
          if (taxa_are_rows(ps)) {
              data = as.matrix(phyloseq::otu_table(ps))
      } else {
          data = as.matrix(t(phyloseq::otu_table(ps)))
      },

    sample_metadata = as.data.frame(phyloseq::sample_data(ps)),
    observation_metadata = as.data.frame(phyloseq::tax_table(ps)), 
    matrix_element_type = "int"
      )
      )

**Comment by itsmisterbrown** [comment]
hi @zhilongjia 

Thanks very much for pointing this out, this is a good catch. I'd actually already written a separate formatting function, **format.ASV.tab**, which is implemented in *most* other functions for such error protection reasons. However, I've clearly forgotten to implement it in **write.dataset.biom**.  Will update immediately.

thanks again!
