### ISSUE TITLE
Issues sourcing the function

### ISSUE THREAD

**Issue by restivve** [itsmisterbrown/marker_gene_processing_scrips#2]
Hi,

I am getting an error message when I try to source the function using this line of code:

source("/Users/bpb/Documents/GitHub/microfiltR/microfiltR_source_code.R")
 
Error message: 
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file '/Users/bpb/Documents/GitHub/microfiltR/microfiltR_source_code.R': No such file or directory
>

**Comment by itsmisterbrown** [comment]
hi,

the issue is because you're trying to source it from the location on my local machine. If you update the path within the source command to where you've downloaded it to on your machine, then it should import smoothly. See below:

`source("your/local/path/to/microfiltR_source_code.R")`
